version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  target-branch: "develop"
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  target-branch: "develop"
